CHANGELOG.md
monitoring/onpremise/grafana/init-configmap.tf

From version `10.x` of Grafana, set the parameter `serve_from_sub_path` to `false`.

fix: Set serve_from_sub_path to false in Grafana

---

storage/onpremise/activemq/README.md
storage/onpremise/activemq/certificates.tf
storage/onpremise/activemq/variables.tf
storage/onpremise/mongodb/README.md
storage/onpremise/mongodb/variables.tf
storage/onpremise/redis/README.md
storage/onpremise/redis/certificates.tf
storage/onpremise/redis/variables.tf

mongo DB validity certificate is now configurable with this [PR](https://github.com/aneoconsulting/ArmoniK.Infra/pull/50)
now I did the  for activeMQ and Redis
validity of certificates was hardcoded to 7 days
=> on prem install will not work anymore after 7 days
fix is :
1 - validity is now 1 year by default
2 - it is now overridable by a parameter : 'validity_period_hours'
both configuration available for modules Redis and activeMQ in storage/onpremise folder

feat: validity period of activemq and redis

---

kubernetes/gcp/gke/main.tf

taints are applied on node
node name for the taint MUST be the same than the name of the nodes
so the code : 
`name = "${var.name}-${node_pool["name"]}"`
was adding name of the cluster before the name of the node
but the user who give the taints in repo armonik don't know it. => a name mismatch will occur and taint will not be applied
after fix :

fix: fix taint in gke

---

monitoring/onpremise/prometheus/main.tf

The current cluster roles rules don't allow scraping of pod metrics.
This fix allows the collection of various metrics such as cpu and memory information

fix: adjust prometheus cluster roles to enable pod metrics scraping

---

armonik/external-data.tf

The resource used in the replace (`data.kubernetes_secret.deployed_object_storage`) needs to be removed as part of the refactoring, as there is a read from a secret that is being removed. 
The PR therefore use the namespace for the dependency

fix: update dummy replace used for dependency

---

armonik/external-data.tf

Implement the proper fix from #154
Even if the implicit dependency is rightfully propagated, the data source is still read during plan because the value is already known. Making it depends on the id of the core configmap ensure the value is *unknown* at plan time.

fix: Kubernetes dependency (cf: #154)

---

armonik/ingress-configmap.tf

These headers break the java client as they are not needed in http2

fix: remove connection http headers from ingress responses

---

storage/onpremise/mongodb/outputs.tf

In prevision of #168 which will slightly modify partitions-in-database jobs by requiring a `MongoDB__AuthSource` env variable to run correctly, this PR preventively treats an error status for this job that would prevent from deploying ArmoniK.
It also updates the `unused_variables` output. As a reminder, this output was added to pass Terraform linting : unused variables were left in the code to avoid breaking change in https://github.com/aneoconsulting/ArmoniK .
This PR simply adds an entry to the `env` output with key `MongoDB__AuthSource` and a value hard-coded to `database`, and also removes the entries `persistent_volume` and `security_context` from the `unused_variables` output.
After #168 and https://github.com/aneoconsulting/ArmoniK/pull/1321 are merged, the test can be done by …

refactor: update MongoDB outputs

---

armonik/partitions-in-database-cron.tf
armonik/partitions-in-database.tf
storage/onpremise/mongodb-sharded/certificates.tf
storage/onpremise/mongodb-sharded/configmap.tf
storage/onpremise/mongodb-sharded/credentials.tf
storage/onpremise/mongodb-sharded/examples/complete/main.tf
storage/onpremise/mongodb-sharded/examples/complete/outputs.tf
storage/onpremise/mongodb-sharded/examples/complete/providers.tf
storage/onpremise/mongodb-sharded/examples/complete/variables.tf
storage/onpremise/mongodb-sharded/examples/complete/versions.tf
storage/onpremise/mongodb-sharded/examples/simple/main.tf
storage/onpremise/mongodb-sharded/examples/simple/outputs.tf
storage/onpremise/mongodb-sharded/examples/simple/providers.tf
storage/onpremise/mongodb-sharded/examples/simple/variables.tf
storage/onpremise/mongodb-sharded/examples/simple/versions.tf
storage/onpremise/mongodb-sharded/locals.tf
storage/onpremise/mongodb-sharded/main.tf
storage/onpremise/mongodb-sharded/outputs.tf
storage/onpremise/mongodb-sharded/persistence.tf
storage/onpremise/mongodb-sharded/secrets.tf
storage/onpremise/mongodb-sharded/variables.tf
storage/onpremise/mongodb-sharded/versions.tf

Described in AEP 004. This PR is meant to treat a previsible bottleneck on ArmoniK's database by enabling a sharded architecture to it.
This PR adds a new module ` mongodb-sharded` that calls a Helm chart deploying a sharded MongoDB (by default [Bitnami's](https://artifacthub.io/packages/helm/bitnami/mongodb-sharded)). It is both out-of-the-box and configurable : number of shards, number of replicas, node selectors and labels for each MongoDB entities, persistence, etc.
The two examples modules test this new module : one deploys it with a complete redefinition of the configuration, the other with all the default values
It is expected to enhance ArmoniK's strong scalability at the cost of simple database configuration. A sharded database is indeed more complex. 
Theses developments were …

feat: deploy a sharded MongoDB

---

monitoring/onpremise/exporters/mongodb-exporter/README.md
monitoring/onpremise/exporters/mongodb-exporter/main.tf
monitoring/onpremise/exporters/mongodb-exporter/outputs.tf
monitoring/onpremise/exporters/mongodb-exporter/variables.tf
monitoring/onpremise/exporters/mongodb-exporter/versions.tf
monitoring/onpremise/prometheus/README.md
monitoring/onpremise/prometheus/prometheus-configmap.tf
monitoring/onpremise/prometheus/variables.tf
storage/onpremise/mongodb/createClusterMonitor.js
storage/onpremise/mongodb/main.tf

We needed a way to extract the metrics that MongoDB already exposes to us for either visualization through Grafana or over-time tracking with Prometheus. These are per-collection and per-operation metrics that can later be used for a more targetted analysis with regards to the database's health and performance.
Added a Kubernetes deployment of Percona's MongoDB metrics exporter, automated the creation of a new ```clusterMonitor``` user to obtain database metrics and changed Prometheus's config map for it to retrieve stats from the exporter's endpoint. 
Tested with a [pre-existing](https://grafana.com/grafana/dashboards/20867-mongodb-dashboard/) dashboard for this exporter. You can also look at the mongodb prometheus metrics (with a ```mongo_``` prefix) in Grafana's metrics tab to see if …

feat: Added Percona's MongoDB exporter to observe database related metrics

---

monitoring/onpremise/prometheus/README.md
monitoring/onpremise/prometheus/variables.tf

Fix deployment break introduced by #175 by replacing `mongo_metrics_exporter_url` `null` default value with empty string.

fix: change default value for MongoDB metrics exporter URL

---

monitoring/onpremise/exporters/node-exporter/README.md
monitoring/onpremise/exporters/node-exporter/locals.tf
monitoring/onpremise/exporters/node-exporter/main.tf
monitoring/onpremise/fluent-bit/locals.tf
monitoring/onpremise/fluent-bit/main.tf

The node selectors are not applied to fluent-bit pods and node_exporters even if they are correctly defined.
Adding the defined node selectors to the daemonset definition
N/A
Pods will be created and scheduled only on the nodes satisfying the node selectors

fix: node selector support for node_exporter and fluent-bit

---

monitoring/onpremise/grafana/dashboard-mongodb.json
monitoring/onpremise/grafana/dashboards-configmap.tf

We'd like to displaying relevant metrics for our MongoDB deployment in order to pinpoint bottlenecks, potential configuration and sizing issues...etc.
Screenshots of the dashboard:
Some metrics also have descriptions that explain how they can relate to certain issues.
Visualizations are indeed accurate. Other than that, not relevant.
Not relevant.

feat: Added dashboard for mongodb monitoring

---

armonik/partitions-in-database-cron.tf

Next to #168, partitions-in-database cron job was in failed status due to missing quoting mark on the connection string, thus leading shell to interprete a '&' in a shell way rather than in a URL way.
Simply quote marks MongoDB connection string in partition-in-database command.
Correction tested on localhost.
Enables cron job to attain Completed status again.

fix: quoting marks missing in partition in database cronjob

---

monitoring/onpremise/fluent-bit/README.md
monitoring/onpremise/fluent-bit/aws.tf
monitoring/onpremise/fluent-bit/configs/output/output-s3.conf
monitoring/onpremise/fluent-bit/configs/service/aws.conf
monitoring/onpremise/fluent-bit/envvars-configmap.tf
monitoring/onpremise/fluent-bit/locals.tf
monitoring/onpremise/fluent-bit/main.tf
monitoring/onpremise/fluent-bit/variables.tf

The logs collected by Fluentbit can be read through Seq but there was no way of exporting them for later analysis for local host deployments of ArmoniK. This PR aims to change that, and also generalize the naming scheme of the log files so as to make it easier to look through them. Which is an absolute necessity for the ArmoniK bench team because of the need to look at past runs.
Made it possible to provide AWS credentials to Fluentbit to enable AWS on localhost (it already uses EKS when using the AWS deployment), to specify a format of the log files as a tfvar. 
Tested log dumping onto the "armonik-logs-testing" bucket. 
Potential impact on FluentBit but it would be very minimal.
You need to allow PutObject on the bucket that you choose to dump logs to.
```json
{
"Version": "2012-10-17", …
```

feat: Export localhost ArmoniK logs to an S3 bucket 

---

armonik/locals.tf
monitoring/onpremise/fluent-bit/configs/filter/filter-kubernetes-daemonset.conf

Log enrichment for kubernetes metadata was not working when fluent-bit was configured on daemon-set.
Configure fluent-bit to fetch kubernetes metadata from Kupe-API instead of kubelet, which was not working.
It also remove the *unused* volume mount on the sidecar that was failing deployment on hosts without /var/fluent-bit/state/
Tested on locahost with K3s and docker.
Apart from fixing the bug, there is no impact.

fix: fluent-bit K8s enrichment

---

storage/aws/elasticache/README.md
storage/aws/elasticache/outputs.tf
storage/aws/elasticache/variables.tf
storage/aws/mq/README.md
storage/aws/mq/variables.tf
storage/aws/s3/README.md
storage/aws/s3/outputs.tf
storage/aws/s3/variables.tf
storage/gcp/gcs/README.md
storage/gcp/gcs/outputs.tf
storage/gcp/gcs/variables.tf
storage/gcp/memorystore/redis/README.md
storage/gcp/memorystore/redis/outputs.tf
storage/gcp/memorystore/redis/variables.tf
storage/onpremise/minio/README.md
storage/onpremise/minio/outputs.tf
storage/onpremise/minio/variables.tf
storage/onpremise/nfs/README.md
storage/onpremise/nfs/outputs.tf
storage/onpremise/nfs/variables.tf
storage/onpremise/redis/README.md
storage/onpremise/redis/outputs.tf
storage/onpremise/redis/variables.tf

In branch main of ArmoniK.Core, the object storage is now dynamic and requires new environment variables to work.
Adds the environment variables related to the dynamic loading of the object storage to the output of the storage modules.
This has been tested on AWS using the latest ArmoniK.Core snapshot (0.30.0-SNAPSHOT.18.220164cc)

feat: Add environment variables for dynamic object storage

---

.github/workflows/pre-commit.yml
storage/onpremise/mongodb-sharded/certificates.tf
storage/onpremise/mongodb-sharded/outputs.tf
storage/onpremise/mongodb-sharded/secrets.tf

- Implement TLS connection for MongoDB in ArmoniK.Core.
- Generated custom certificates to enable TLS for MongoDB.
- Removed the use of **chain.pem** and replaced it with a standalone certificate.
- This branch was tested with ArmoniK deployments in the following environments:
- Localhost
- AWS
- GCP 
- Secures MongoDB connections by enabling TLS in our deployments.
- None

feat: implem config for new tls on core

---

storage/aws/mq/main.tf

Update Active mq in AWS to 5.18 requires to set the variable auto_minor_version_upgrade to true.
In order to complete the update in the [PR -1356 : chore: update active mq version to 5.18.6 in aws](https://github.com/aneoconsulting/ArmoniK/pull/1356)
Setup the variable auto_minor_version_upgrade to true will handle the case of updating active mq version.
The deployment should work correctly when setting the engine version of active mq to 5.18 from 5.17.6.
Update the package will be possible.
[Any additional information that reviewers should be aware of.]

chore: set auto_minor_version_upgrade to true in amazon mq

---

service-account/aws/main.tf
service-account/aws/outputs.tf
service-account/aws/variables.tf
service-account/aws/versions.tf
storage/aws/s3/README.md
storage/aws/s3/main.tf
storage/aws/s3/variables.tf
storage/aws/sqs/main.tf
storage/aws/sqs/outputs.tf
storage/aws/sqs/variables.tf
storage/aws/sqs/versions.tf

SQS was added to ArmoniK.Core but was never supported in ArmoniK.Infra.
Added an optional kubernetes service account that can be associated with an AWS role that has access to SQS queues, and exported certain environment variables for ArmoniK.Core to access.
Manually tested through deployments.
A bit intrusive in terms of ArmoniK's configuration (`parameters.tfvars`) because of the use of a service account.
None.

feat: Added SQS support to ArmoniK.Infra

---

storage/onpremise/activemq/README.md
storage/onpremise/activemq/main.tf
storage/onpremise/activemq/variables.tf

Customize the module of Active MQ with the resources and optional heap parameters.
I added 3 optional variables (limits, requests and activemq_opts_memory) in the active mq module. These variables will be put in the container of the active mq resource. Limits and requests contain the vCPU and memory resources and the activemq_opts_memory contains the values to be given to the heap parameters.
The Active MQ pod should contain the correct values of the resources (limits and requests of CPU and memory) and environment variable for "ACTIVEMQ_OPTS_MEMORY".
The user can customize more the active mq module in the setup phase.
[Any additional information that reviewers should be aware of.]

feat: add resources and activemq opts memory variables in the activemq module

---

.pre-commit-config.yaml

Avoid files mixing LF and CR/LF files ending.
Add a job in the pre-commit file to check mixed file endings.
Properly detects files with mexed line endings.
Does not allow to merge files with mixed line endings.
None

fix: do not allow mixed line endings via pre-commit

---

kubernetes/aws/eks/README.md
kubernetes/aws/eks/ebs-csi.tf
kubernetes/aws/eks/efs-csi.tf
kubernetes/aws/eks/examples/complete/main.tf
kubernetes/aws/eks/examples/complete/variables.tf
kubernetes/aws/eks/examples/simple/main.tf
kubernetes/aws/eks/variables.tf
storage/onpremise/mongodb-sharded/persistence.tf
storage/onpremise/mongodb/persistent-volume.tf

This PR introduces the capacity to provision EBS persistent volumes for MongoDB pods on EKS. Our sharded MongoDB deployment is unstable without persistence while we only supported persistence through EFS, which was not performance-friendly.
This PR enables to deploy the standard EBS CSI on EKS while disabling TLS mount option for the EBS volumes to be provisioned, as it seems to not be supported by the provisioner yet.
Successfully deployed the driver on AWS and was able to provision EBS volumes for MongoDB and MongoDB sharded pods.
Might have a significant impact on performance for our sharded MongoDB deployment.
On the mid-term, TLS mounting of EBS volumes would be to implement.

feat: add EBS volume provisioning support for MongoDB

---

armonik/README.md
armonik/outputs.tf

Needed a way to easily point the ArmoniK CLI to your current deployment.
Autogenerate an additional ArmoniK CLI config as well as the necessary certificates for connection via TLS. 
Tested with both TLS enabled and disabled on a local host deployment. 
Not applicable.
Not applicable.

feat: Autogenerated config file for ArmoniK CLI

---

storage/aws/mq/outputs.tf
storage/onpremise/activemq/outputs.tf
storage/onpremise/rabbitmq/outputs.tf

Simplify TLS configuration by using a single parameter (the scheme) to indicate whether TLS should be applied.
Use only **Amqp__Scheme** parameter to control TLS for AMQP connections, reducing configuration complexity
Tests were ran on localhost for RabbitMQ and ActiveMQ. 
Another was ran for AmazonMQ
Simplifies TLS configuration, reducing potential errors and improving code clarity. No significant performance impact.
Note that this change will not be functional with older versions of Core, as the old **Amqp__Ssl** parameter is checked in the old Core version. Ensure that you are using the latest version of Core to benefit from this simplified configuration.

fix: remove SSL parameter in outputs file for ActiveMQ and RabbitMQ

---

.pre-commit-config.yaml
renovate.json

Renovate creates a single PR for all kind of dependency update.
Splits the PR into multiple groups:
- Docker images
- Terraform modules
- Terraform providers
- Terraform providers for examples
- Helm charts
- Github actions
- Other packages

ci: Split renovate PRs into groups

---

.pre-commit-config.yaml
renovate.json

Renovate packageRules are ordered from lower precedence to higher precedence, but we ordered them from most specific to least specific. Therefore, all updates ended-up into the least specific (but highest precedence) rule.
Move the least specific rules first to match the precedence of Renovate.
Cannot be tested before landing on main.

ci: Proper order for Renovate packageRules

---

armonik/compute-plane-configmap.tf

There was an issue where log configuration and compute configuration were not propagated to compute pods.
Target the compute-all aggregation  instead of compute.
Local deployment shows that log configuration is now properly propagated to compute plane.

fix: compute plane configuration

---

armonik/README.md
armonik/versions.tf
kubernetes/aws/addons/efs-csi/README.md
kubernetes/aws/addons/efs-csi/examples/complete/README.md
kubernetes/aws/addons/efs-csi/examples/complete/versions.tf
kubernetes/aws/addons/efs-csi/versions.tf
kubernetes/aws/eks/README.md
kubernetes/aws/eks/examples/complete/README.md
kubernetes/aws/eks/examples/complete/versions.tf
kubernetes/aws/eks/examples/simple/README.md
kubernetes/aws/eks/examples/simple/versions.tf
kubernetes/aws/eks/versions.tf
monitoring/onpremise/keda/README.md
monitoring/onpremise/keda/versions.tf
monitoring/onpremise/metrics-server/README.md
monitoring/onpremise/metrics-server/versions.tf
storage/onpremise/mongodb-sharded/examples/complete/versions.tf
storage/onpremise/mongodb-sharded/examples/simple/versions.tf
storage/onpremise/mongodb-sharded/versions.tf
storage/onpremise/mongodb/README.md
storage/onpremise/mongodb/examples/complete/README.md
storage/onpremise/mongodb/examples/complete/versions.tf
storage/onpremise/mongodb/examples/simple/README.md
storage/onpremise/mongodb/examples/simple/versions.tf
storage/onpremise/mongodb/versions.tf
storage/onpremise/rabbitmq/README.md
storage/onpremise/rabbitmq/versions.tf

Helm provider has been updated to plugin framework, and removed blocks from provider configuration.
It appears that this new version is not yet stable enough: https://github.com/hashicorp/terraform-provider-helm/issues/1637
AWS provider uptated to 6.0 which has a few incompatiblities, especially regarding elastic accelerators.
Restrict the helm provider version to `< 3.0.0` and aws provider version to `< 6.0.0`.

fix: Restrict Helm and AWS versions

---

monitoring/onpremise/seq/main.tf

Added an environment variable to disable Seq’s forced admin authentication on first run.
Allows Seq to start without requiring an admin password, useful for dev/test environments.
* [] Local testing done (Seq starts without errors)

fix: Seq noauthentification behavior

---

armonik/locals.tf

Newer version of ArmoniK.Core requires the environment variable Pollster__PartitionId.
Add Pollster__PartitionId to the list of supported queues.

refactor: Add Pollster__PartitionId

---

armonik/authentication-in-database.tf
armonik/partitions-in-database-cron.tf
armonik/partitions-in-database.tf
monitoring/onpremise/exporters/mongodb-exporter/README.md
monitoring/onpremise/exporters/mongodb-exporter/main.tf
monitoring/onpremise/exporters/mongodb-exporter/variables.tf
storage/atlas/README.md
storage/atlas/credentials.tf
storage/atlas/main.tf
storage/atlas/outputs.tf
storage/atlas/secrets.tf
storage/onpremise/mongodb-sharded/certificates.tf
storage/onpremise/mongodb-sharded/configmap.tf
storage/onpremise/mongodb-sharded/credentials.tf
storage/onpremise/mongodb-sharded/outputs.tf
storage/onpremise/mongodb-sharded/secrets.tf
storage/onpremise/mongodb/README.md
storage/onpremise/mongodb/createClusterMonitor.tftpl
storage/onpremise/mongodb/credentials.tf
storage/onpremise/mongodb/main.tf
storage/onpremise/mongodb/outputs.tf
storage/onpremise/mongodb/secrets.tf

Making sure the previous exporter worked with Atlas MongoDB as well as needing to do various minor improvements. 
- Made changes to the `partitions-in-database` job and the `partitions-in-database` cron job. These used to fail when deploying sharded MongoDB on premise because the SRV record lookup isn't properly configured when deploying locally.  
- Added SAN for mongodb-sharded's certificate (Having only the common name specified results in a x509 error)
- Handled specific deployment requirements for 5 different ways of deploying MongoDB  
- Properly created the monitoring user in the different MongoDB deployments.
- Passing in the different modules instead of the URL for cleaner/easier deployment.
This has been tested both locally and on AWS (See the PR that adds the exporter to the …

refactor: MongoDB exporter refactor 

---

.github/workflows/make-release.yml

In some cases, the version computed by codacy does not match what we really want.
Add a possibility to override the release version by specifying a project variable named `OVERRIDE_RELEASE_VERSION` with the expected version.
The mechanism has been tested in ArmoniK.Core.
The override variable must be emptied after the release.

ci: Support for OVERRIDE_RELEASE_VERSION
